version: '3'

env:
  PYTHONPATH: "{{ .PWD }}/src"
  DJANGO_SETTINGS_MODULE: "market.market.settings"

tasks:
  update-dev-env:
    cmds:
      - pip install -r requirements/dev.txt
  createsuperuser:
    cmds:
      - django-admin createsuperuser
  runserver:
    cmds:
      - django-admin runserver
  shell:
    cmds:
      - django-admin shell
  migrate:
    cmds:
      - django-admin makemigrations
      - django-admin migrate
  dumpdata-full:
    cmds:
      - django-admin dumpdata --exclude auth.permission --exclude contenttypes --exclude admin.logentry --exclude auth.user --exclude sessions.session --indent 4 -o src/market/fixtures/full_db.json
  loaddata-full:
    cmds:
      - django-admin createcachetable
      - django-admin loaddata src/market/fixtures/full_db.json
  loaddata--apps:
    cmds:
      - django-admin loaddata src/market/fixtures/full_db.json --app settingsapp.CacheTime
      - django-admin loaddata src/market/fixtures/full_db.json --app categories.Category
      - django-admin loaddata src/market/fixtures/full_db.json --app products.Product
      - django-admin loaddata src/market/fixtures/full_db.json --app banner_app.BannerSlider
